function branch-protection-install --description "Enable/disable branch protection for this repo"
    set -l local_config "lefthook-local.yml"
    set -l main_config "lefthook.yml"
    set -l protect_config "$HOME/.config/lefthook/branch-protection.yml"
    set -l marker "# auto-generated by protect-branch"

    if test "$argv[1]" = "off"
        # Disable protection
        if test -f $local_config
            rm $local_config
            # Remove main config only if it was auto-generated by us
            if test -f $main_config
                if head -1 $main_config | grep -q "$marker"
                    rm $main_config
                end
            end
            lefthook uninstall
            echo "Branch protection disabled"
        else
            echo "Branch protection is not enabled"
        end
        return
    end

    # Enable protection
    if not test -d .git
        echo "ERROR: Not a git repository"
        return 1
    end

    if not test -f $protect_config
        echo "ERROR: Protection config not found: $protect_config"
        return 1
    end

    # Create minimal lefthook.yml if it doesn't exist
    if not test -f $main_config
        echo "$marker
# Actual config is in lefthook-local.yml (gitignored)
" > $main_config
        # Add to repo-local exclude (not tracked by git)
        set -l exclude_file ".git/info/exclude"
        if not grep -q "^lefthook.yml\$" $exclude_file 2>/dev/null
            echo "lefthook.yml" >> $exclude_file
        end
    end

    echo "extends:
  - $protect_config" > $local_config

    lefthook install
    echo "Branch protection enabled (main, master, develop, production)"
end
