# Dark powered asynchronous completion framework for neovim/Vim8
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_source = ['LanguageClient-neovim']
on_event = ['InsertEnter']
hook_source = '''
  source ~/.vim/rc/dein/plugins/deoplete.rc.vim
  call deoplete#enable()
'''
hook_post_update = 'UpdateRemotePlugins'

[[plugins]]
repo = 'Shougo/neco-syntax'
depends = 'deoplete.nvim'
on_event = ['InsertEnter']

# Include completion framework for neocomplete/deoplete
[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_source = ['deoplete.nvim']

# Print documents in echo area.
[[plugins]]
repo = 'Shougo/echodoc.vim'
on_source = ['deoplete.nvim']
hook_add = 'let g:echodoc_enable_at_startup = 1'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_source = '''
  let g:rustfmt_autosave = 0
  let g:rust_fold = 1
'''

[[plugins]]
repo = 'rhysd/rust-doc.vim'

# [[plugins]]
# repo = 'dart-lang/dart-vim-plugin'
# on_ft = 'dart'
# hook_source = '''
#   let dart_html_in_string=v:vital_import_without_let
#   let dart_style_guide = 2
#   let dart_format_on_save = 1
# '''

[[plugins]]
repo = 'machakann/vim-vimhelplint'
on_ft = 'help'
[plugins.ftplugin]
help = '''
  nnoremap <silent><buffer> ,r  :<C-u>VimhelpLint!<CR>
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
  let g:go_def_mode = 'gopls'
  let g:go_def_mapping_enabled = 1
  let g:go_gocode_propose_builtins = 1
  let g:go_list_type = "quickfix"
  let g:go_fmt_command = "goimports"
  let g:go_highlight_types = 1
  let g:go_highlight_functions = 1
  let g:go_highlight_function_calls = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_extra_types = 1

  autocmd FileType go nmap <leader>r <Plug>(go-run)
  autocmd FileType go nmap <leader>t <Plug>(go-test)
  autocmd FileType go nmap <leader>b :<C-u>call <SID>build_go_files()<CR>
  " autocmd FileType go nmap <Leader>c <Plug>(go-coverage-toggle)
  autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4
'''

[[plugin]]
repo = 'AndrewRadev/splitjoin.vim'
on_ft = ['go']

# [[plugins]]
# repo = 'pbogut/deoplete-elm'

# [[plugins]]
# repo = 'zchee/deoplete-docker'
